name: Fetch Starred Repositories

on:
  schedule:
    # 每天 UTC 时间 0 点运行
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  fetch-starred-repos:
    runs-on: ubuntu-latest
    
    permissions: 
      contents: write 
      pages: write 
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Fetch starred repositories
        uses: ./action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}
          output-file: ./docs/data/starred-repos.json
          # 在生产环境中不生成简化版本文件
          simple-output-file: ./docs/data/starred-repos-simple.json
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
      
      - name: Setup Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
          
      - name: Install frontend dependencies
        run: pnpm install
          
      - name: Build frontend
        run: pnpm run build
          
      - name: Prepare deployment files
        run: |
          # 删除可能存在的简化版本文件
          rm -f docs/data/starred-repos-simple.json
          # Copy built frontend files to docs directory
          cp -r dist/* docs/ || true
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
