name: Update Frontend Only

on:
  workflow_dispatch: # 允许手动触发

jobs:
  update-frontend:
    runs-on: ubuntu-latest
    
    permissions: 
      contents: write 
      pages: write 
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
      
      - name: Setup Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
          
      - name: Install frontend dependencies
        run: pnpm install
          
      - name: Build frontend
        run: pnpm run build
          
      - name: Download data directory from gh-pages branch to dist
        run: |
          echo "Downloading data directory from gh-pages branch to dist..."
          # Fetch the gh-pages branch
          git fetch origin gh-pages
          # Checkout data directory from gh-pages branch to dist directory
          git checkout origin/gh-pages -- data/
          # Copy data directory to dist folder
          cp -r data/ dist/
          echo "Data directory copied to dist directory"
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
